# Generated by Django 4.1.6 on 2023-02-17 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CSVFile',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('file_path', models.TextField(db_column='file_path')),
        #         ('file_name', models.TextField(db_column='file_name')),
        #         ('timestamp', models.DateTimeField(auto_now_add=True)),
        #         ('description', models.TextField(blank=True, default='')),
        #         ('is_public', models.BooleanField(default=False)),
        #         ('is_public_orgs', models.BooleanField(default=False)),
        #         ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to=settings.AUTH_USER_MODEL)),
        #         ('registered_organizations', models.ManyToManyField(blank=True, related_name='uploaded_files', to='organizations.organization')),
        #     ],
        #     options={
        #         'unique_together': {('author', 'file_name')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='TagCsvFile',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('text', models.CharField(max_length=100)),
        #         ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='data.csvfile')),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.DeleteModel(
        #     name='DataAccel',
        # ),
    ]
