# Generated by Django 4.1.6 on 2023-03-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_csvfile_tagcsvfile_delete_dataaccel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file_path',
            field=models.TextField(db_column='file_path', unique=True),
        ),
    ]
