# Generated by Django 4.1.6 on 2023-03-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_csvfile_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='file_path',
            field=models.TextField(blank=True, db_column='file_path', null=True, unique=True),
        ),
    ]
