# Generated by Django 4.1.4 on 2023-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_csvfile_file_name_alter_csvfile_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
