# Generated by Django 4.1.4 on 2023-09-19 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0009_csvfile_download_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.TextField(blank=True, db_column='folder_name', null=True)),
                ('folder_path', models.TextField(blank=True, db_column='folder_path', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('is_public_orgs', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='data.folder')),
                ('registered_organizations', models.ManyToManyField(blank=True, related_name='uploaded_folders', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='csvfile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='data.folder'),
        ),
    ]
