# Generated by Django 4.1.6 on 2023-09-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0010_folder_csvfile_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(blank=True, db_column='file_path', null=True)),
                ('file_name', models.TextField(db_column='file_name', unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('is_public_orgs', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('registered_organizations', models.ManyToManyField(blank=True, related_name='uploaded_files', to='organizations.organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='csvfile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='registered_organizations',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.AlterField(
            model_name='tagcsvfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='data.file'),
        ),
    ]
