# Generated by Django 4.1.6 on 2023-09-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_file_alter_csvfile_unique_together_and_more'),
        ('social', '0007_alter_review_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFile',
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('author', 'file_name')},
        ),
    ]
