# Generated by Django 4.1.6 on 2023-09-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_delete_csvfile_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcsvfile',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='data.file'),
        ),
    ]
