# Generated by Django 4.1.6 on 2023-09-26 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0013_alter_tagcsvfile_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('author', 'file_path')},
        ),
    ]
