# Generated by Django 4.1.6 on 2023-09-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.TextField(db_column='file_name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.TextField(blank=True, db_column='file_path', null=True, unique=True),
        ),
    ]
