# Generated by Django 4.1.4 on 2023-09-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_file_original_file_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagCsvFile',
            new_name='TagFile',
        ),
    ]
