# Generated by Django 4.1.4 on 2023-12-22 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_description_and_more'),
        ('data', '0018_dataset_file_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='name',
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_public_orgs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='registered_organizations',
            field=models.ManyToManyField(blank=True, related_name='uploaded_datasets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data.dataset'),
        ),
        migrations.DeleteModel(
            name='TagFile',
        ),
        migrations.AddField(
            model_name='tagdataset',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_set', to='data.dataset'),
        ),
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.RemoveField(
            model_name='file',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_public_orgs',
        ),
        migrations.RemoveField(
            model_name='file',
            name='registered_organizations',
        ),
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
    ]
