# Generated by Django 4.1.4 on 2023-12-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_dataset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='original_file_name',
        ),
    ]
