# Generated by Django 5.0.1 on 2024-04-04 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="bio",
        ),
    ]
