# Generated by Django 4.1.6 on 2023-02-17 20:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_csvfile_tagcsvfile_delete_dataaccel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Conversation',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=200)),
        #         ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_conversation_set', to=settings.AUTH_USER_MODEL)),
        #         ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_conversation_set', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Message',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('text', models.CharField(max_length=255)),
        #         ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_message_set', to=settings.AUTH_USER_MODEL)),
        #         ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo_message_set', to='social.conversation')),
        #         ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_message_set', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.AlterUniqueTogether(
        #     name='review',
        #     unique_together=set(),
        # ),
        # migrations.AddField(
        #     model_name='review',
        #     name='file',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='data.csvfile'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='review',
        #     name='rating',
        #     field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        # ),
        # migrations.AlterField(
        #     model_name='review',
        #     name='author',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='review',
        #     unique_together={('author', 'file')},
        # ),
        # migrations.CreateModel(
        #     name='NotificationReview',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('text', models.CharField(max_length=300)),
        #         ('read', models.BooleanField(default=False)),
        #         ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notification_post_set', to=settings.AUTH_USER_MODEL)),
        #         ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_post_set', to='social.review')),
        #         ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification_post_set', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='NotificationMessage',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('text', models.CharField(max_length=300)),
        #         ('read', models.BooleanField(default=False)),
        #         ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_message_set', to='social.message')),
        #         ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_notification_message_set', to=settings.AUTH_USER_MODEL)),
        #         ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_notification_message_set', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
    ]
