# Generated by Django 4.1.6 on 2023-09-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_file_alter_csvfile_unique_together_and_more'),
        ('social', '0006_notificationmessage_title_notificationnews_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='data.file'),
        ),
    ]
