# Generated by Django 4.1.4 on 2023-12-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_remove_file_original_file_name'),
        ('social', '0007_alter_review_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='data.dataset'),
        ),
    ]
